color = input('Please type your favorite color: ')
print('Your favorite color is '+color + '!')
print('Why is '+ color + ' your favorite color?'); why = input()
print('Your favorite color is ' + color + ' because ' + why + '!')
print('That is very neat. Thanks for sharing!')